In [1]:
import numpy as np

In [2]:
class Layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.around(np.random.randn(n_inputs, n_neurons),2)
        self.biases = np.around(np.random.randn(1, n_neurons),2)

    def calculate_output(self, input):
        self.input=np.array(input)
        print("I",self.input,self.input.shape)
        print("W",self.weights,self.weights.shape)
        p = np.dot(self.input,self.weights)
        print("P",p,p.shape)
        weighted_sum = p + self.biases
        self.output = self.activation_function(weighted_sum)
        print("O",self.output,self.output.shape)
        return self.output


    def calculate_delta(self, error, output):
        return error * self.derivative_activation_function(output)

    def update_weights(self, input, delta, learning_rate):
        if delta.shape[1] != input.shape[0]:
            input=input.T
            # delta = delta.reshape(input.shape[0],-1)
            # raise ValueError("The size of delta must be equal to the number of rows of input")
        self.weights += learning_rate * np.dot(delta,input).T
        self.biases += learning_rate * np.sum(delta)

    def activation_function(self, x):
        # return 1 / (1 + np.exp(-x))
        return x

    def derivative_activation_function(self, x):
        # return np.exp(-x) / (1 + np.exp(-x))**2
        return x

def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

def relu(x):
    return np.maximum(x, 0)

def relu_derivative(x):
    return np.array(x >= 0).astype('int')




In [5]:
class NeuralNetwork:
    def __init__(self, layers):
        np.random.seed(1)
        self.layers = layers[1:]
        for layer in self.layers:
            print(layer.weights,layer.biases)
          

    def predict(self, input):
        output = input
        for layer in self.layers:
            output = layer.calculate_output(output)
        return output

    def train(self, input, expected_output, learning_rate):
        output = self.predict(input)
        error = expected_output - output
        print("val",output)
        print("E",expected_output," - ",output," = ",error)

        # for i in range(len(self.layers)-1, -1, -1):
        #     print(i)
        #     layer = self.layers[i]
        #     # prev_layer = self.layers[i-1] if i>0 else 0
        #     input=layer.input
        #     output = layer.output
        #     print("I",input,input.shape)
        #     print("O",output,output.shape)
        #     print("W",layer.weights,(layer.weights).shape)
        #     if i == len(self.layers) - 1:
        #         print("E",error,error.shape)
        #         layer.delta = layer.calculate_delta(error, output)
        #         print("Delta",i,layer.delta,layer.delta.shape)
        #         layer.weights += learning_rate * np.dot(layer.delta.T,input).T
        #         layer.biases += learning_rate * np.sum(layer.delta)
        #         print("Updated Weights",i,layer.weights)
        #     else:
        #         next_layer = self.layers[i+1]
        #         # print("NLD",next_layer.delta)
        #         # print("NLW",next_layer.weights)
        #         layer.delta = layer.calculate_delta(np.dot(next_layer.delta, next_layer.weights.T), layer.output)
        #         print("Delta",i,layer.delta,layer.delta.shape)
        #         layer.update_weights(input, layer.delta, learning_rate)
        #         print("Updated Weights",i,layer.weights)

        

In [6]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

input_layer = Layer(2, 2)
hidden_layer_1 = Layer(2, 2)
h2= Layer(2,3)
output_layer = Layer(3, 1)

nn = NeuralNetwork([input_layer, hidden_layer_1, h2,
                    output_layer])

for i in range(1):
    # for j in range(len(X)):
    for j in range(1):
        nn.train(X[j], y[j], 0.001)

print(nn.predict(np.array([0, 0])))

[[ 1.74 -0.76]
 [ 0.32 -0.25]] [[ 1.46 -2.06]]
[[-0.32 -0.38  1.13]
 [-1.1  -0.17 -0.88]] [[ 0.04  0.58 -1.1 ]]
[[1.14]
 [0.9 ]
 [0.5 ]] [[0.9]]
I [0 0] (2,)
W [[ 1.74 -0.76]
 [ 0.32 -0.25]] (2, 2)
P [0. 0.] (2,)
O [[ 1.46 -2.06]] (1, 2)
I [[ 1.46 -2.06]] (1, 2)
W [[-0.32 -0.38  1.13]
 [-1.1  -0.17 -0.88]] (2, 3)
P [[ 1.7988 -0.2046  3.4626]] (1, 3)
O [[1.8388 0.3754 2.3626]] (1, 3)
I [[1.8388 0.3754 2.3626]] (1, 3)
W [[1.14]
 [0.9 ]
 [0.5 ]] (3, 1)
P [[3.615392]] (1, 1)
O [[4.515392]] (1, 1)
val [[4.515392]]
E [0]  -  [[4.515392]]  =  [[-4.515392]]
I [0 0] (2,)
W [[ 1.74 -0.76]
 [ 0.32 -0.25]] (2, 2)
P [0. 0.] (2,)
O [[ 1.46 -2.06]] (1, 2)
I [[ 1.46 -2.06]] (1, 2)
W [[-0.32 -0.38  1.13]
 [-1.1  -0.17 -0.88]] (2, 3)
P [[ 1.7988 -0.2046  3.4626]] (1, 3)
O [[1.8388 0.3754 2.3626]] (1, 3)
I [[1.8388 0.3754 2.3626]] (1, 3)
W [[1.14]
 [0.9 ]
 [0.5 ]] (3, 1)
P [[3.615392]] (1, 1)
O [[4.515392]] (1, 1)
[[4.515392]]
