In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
from scipy import stats

In [ ]:
x=np.array([1,2,3,4])
y=np.array([1,2,3,4]).resize(2,2)
print(x)
print(y)

[1 2 3 4]
None


In [ ]:
x=np.zeros(dtype=int,shape=(5,5))
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
x=np.ones((1,5))
print(x)

[[1. 1. 1. 1. 1.]]


In [ ]:
x=np.random.randint(10,size=(2,3))
print(x)
y=x.min(axis=0)
print(y)
y=x.min(axis=1)
print(y)

[[1 6 0]
 [9 4 7]]
[1 4 0]
[0 4]


100 Rand Numbers between 60-260 & Find mean, median, mode, std

In [ ]:
x=np.random.randint(low=60,high=260,size=100)
x

array([152, 143, 104, 186, 117, 207, 159, 231,  85, 188, 147,  61, 160,
        90, 101,  77, 156, 134, 212, 112,  87, 229, 146, 245, 189,  86,
       211, 246, 125,  84, 183, 186,  64, 213, 213, 159, 136, 143, 196,
       195, 167, 198, 236, 229, 122,  79,  99, 115, 112, 156, 183, 182,
       121, 227, 248, 111, 170, 146, 163, 134,  72, 145, 210, 188, 217,
       155,  62, 118, 213, 161, 140, 213,  95, 259, 168, 133, 118, 146,
       245, 147, 224, 224, 225,  71, 150,  85, 150, 248, 155, 127,  90,
       198, 142,  90, 246, 147,  62, 125, 205, 122])

In [ ]:
me=x.mean()
print(me)
md=np.median(x)
print(md)
mo=stats.mode(x)
print(mo[0])

156.47
151.0
[213]


**FINDING MODE**

Method 1

In [ ]:
def mode(x):
  values,cnt=np.unique(x,return_counts=True)
  # print(values)
  # print(cnt)
  mo=np.argmax(cnt)
  # print(mo)
  return values[mo]

print(mode(x))

[ 61  62  64  71  72  77  79  84  85  86  87  90  95  99 101 104 111 112
 115 117 118 121 122 125 127 133 134 136 140 142 143 145 146 147 150 152
 155 156 159 160 161 163 167 168 170 182 183 186 188 189 195 196 198 205
 207 210 211 212 213 217 224 225 227 229 231 236 245 246 248 259]
[1 2 1 1 1 1 1 1 2 1 1 3 1 1 1 1 1 2 1 1 2 1 2 2 1 1 2 1 1 1 2 1 3 3 2 1 2
 2 2 1 1 1 1 1 1 1 2 2 2 1 1 1 2 1 1 1 1 1 4 1 2 1 1 2 1 1 2 2 2 1]
58
213


Method -2 

In [ ]:
def mode(x):
  d={}
  k=0
  v=0
  for i in x:
    d[i]=d.get(i,0)+1
    if d[i]>v:
      k=i
      v=d[i]
  print(d)
  return k

print(mode(x))

{152: 1, 143: 2, 104: 1, 186: 2, 117: 1, 207: 1, 159: 2, 231: 1, 85: 2, 188: 2, 147: 3, 61: 1, 160: 1, 90: 3, 101: 1, 77: 1, 156: 2, 134: 2, 212: 1, 112: 2, 87: 1, 229: 2, 146: 3, 245: 2, 189: 1, 86: 1, 211: 1, 246: 2, 125: 2, 84: 1, 183: 2, 64: 1, 213: 4, 136: 1, 196: 1, 195: 1, 167: 1, 198: 2, 236: 1, 122: 2, 79: 1, 99: 1, 115: 1, 182: 1, 121: 1, 227: 1, 248: 2, 111: 1, 170: 1, 163: 1, 72: 1, 145: 1, 210: 1, 217: 1, 155: 2, 62: 2, 118: 2, 161: 1, 140: 1, 95: 1, 259: 1, 168: 1, 133: 1, 224: 2, 225: 1, 71: 1, 150: 2, 127: 1, 142: 1, 205: 1}
213


**COMMANDS**

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!root

/bin/bash: root: command not found


In [ ]:
!cd ..
!ls

sample_data


**FILE UPLOAD FROM GOOGLE DRIVE**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
!ls

drive  sample_data


In [ ]:
!cd drive

In [ ]:
!ls

drive  sample_data


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path="/content/drive/MyDrive/MachineLearning/19-12-2022/sample.csv"

In [ ]:
df=pd.read_csv(path)
print(df)

   height  weight
0     145      67
1     155      57
2     164      65
3     176      55
4     149      45
